/**
 * Server Build Script for Vercel Deployment
 *
 * Bundles server.ts (and all its imports) into a single ESM file at
 * `api/server-bundle.mjs`. A thin `api/index.js` (also ESM) re-exports
 * the handler from this bundle.
 *
 * Why ESM? package.json has "type": "module" so all .js files are ESM.
 * We use a .mjs bundle so the format is explicit and unambiguous.
 *
 * Run via: node scripts/build-server.mjs
 * Called automatically by: npm run build (after vite build)
 */
import { build } from 'esbuild';
import { writeFileSync, existsSync, mkdirSync, unlinkSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const apiDir = path.join(root, 'api');
const tmpEntry = path.join(root, 'scripts', '_vercel_entry.ts');

// Ensure api/ directory exists
if (!existsSync(apiDir)) {
  mkdirSync(apiDir, { recursive: true });
}

// Temporary entry file that imports the Express app and exports a handler
writeFileSync(tmpEntry, `
import 'dotenv/config';
import { app } from '../server';

// Vercel handler — default export called for each request
export default function handler(req, res) {
  // Restore original URL from Vercel x-matched-path header
  // Vercel rewrites /api/v1/health → /api/index.js, losing path info
  const matchedPath = req.headers['x-matched-path'] || '';
  if (matchedPath && matchedPath.startsWith('/api')) {
    req.url = matchedPath;
  }
  return app(req, res);
}
`);

console.log('[build-server] Bundling server.ts into api/server-bundle.mjs (ESM for Vercel)...');

try {
  await build({
    entryPoints: [tmpEntry],
    bundle: true,
    platform: 'node',
    target: 'node18',
    format: 'esm',
    outfile: path.join(apiDir, 'server-bundle.mjs'),
    // Keep npm packages as external — available in node_modules at Vercel runtime
    packages: 'external',
    sourcemap: false,
    minify: false,
    logLevel: 'info',
  });

  console.log('[build-server] ✓ api/server-bundle.mjs written');

  // Write a thin api/index.js wrapper that re-exports the handler
  // This is what Vercel calls for each request
  writeFileSync(path.join(apiDir, 'index.js'), `
// Auto-generated by scripts/build-server.mjs — DO NOT EDIT
import handler from './server-bundle.mjs';
export default handler;
`.trimStart());

  console.log('[build-server] ✓ api/index.js wrapper written');
  console.log('[build-server] ✓ Server build complete — ready for Vercel deployment');
} finally {
  try { unlinkSync(tmpEntry); } catch (_) {}
}
